### ISSUE TITLE
Brazilian Portuguese translation to the site

### ISSUE THREAD

**Issue by isaacrafael** [Warzone2100/wz2100.net#29]
I would like to be able to help translate the site into Brazilian Portuguese, through Crowdin. Could you add that language to the list?

**Comment by past-due** [comment]
> I would like to be able to help translate the site into Brazilian Portuguese, through Crowdin. Could you add that language to the list?

Added: https://crowdin.com/project/wz2100net/pt-BR

Please feel free to request translator access on Crowdin. 👍

**Comment by isaacrafael** [comment]
Okay. I'll wait, thanks!

**Comment by past-due** [comment]
@isaacrafael I believe we've finally fixed the language code collision issue. pt-BR is now available here: https://crowdin.com/project/wz2100net/pt-BR
