### ISSUE TITLE
Tags at the German translated website are not working properly

### ISSUE THREAD

**Issue by highlander1599** [Warzone2100/wz2100.net#38]
As you can see in the picture below you have "Veröffentlichungen" and "Releases" as tags despite all tags are translated at Crowding. Also, there are only 5 tags in total despite you have 7 at the not translated site.

![Screenshot 2021-04-07 16 55 01](https://user-images.githubusercontent.com/47194838/113888842-fc766800-97c2-11eb-93f3-669dbacebb47.png)

**Comment by past-due** [comment]
Should now be fixed with a sync of the latest translations. 👍
