### ISSUE TITLE
On Cloudflare

### ISSUE THREAD

**Issue by Triloworld** [Warzone2100/wz2100.net#55]
Hi @past-due 
Maybe you can post it on Cloudflare Pages? Cache fully globally free and automatic new version. Can help if you like :)
This can speed up opening website for first time in some places where internet isn't as fast due to edge server that service provide. Some option will be automatically and some need to be enable.
I see netlify toml file but I don't see usage of it. Cloudflare Pages can use that too.
Love to push little project into future :)

As a static page Speed Test is fine: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwz2100.net%2F&form_factor=mobile
Some new issues will be created to adres small fixes: sizes of images inline, swap font for start. Some Cloudflare fix automatically :)

**Comment by past-due** [comment]
Hi @Triloworld,

Despite these builds being initially published to GitHub Pages, the main site itself is already behind Cloudflare's CDN. 👍

**Comment by Triloworld** [comment]
Yeah, but Cloudflare Pages will help with some fixes and is proper place to host website. 
Thats good one :) thx for reply
