### ISSUE TITLE
Visible link to an official maps/mods publishing site needed

### ISSUE THREAD

**Issue by Zispah** [Warzone2100/wz2100.net#58]
The Forums and Addons sites has gone inactive. Currently there are no active organized place for maps/mods, which makes nearly all people play the game without mods or new maps. Create and provide a visible link to such a place and include a guide to install them in the same website to fix the problem.

**Comment by maxsupermanhd** [comment]
There is unofficial map portal at https://wz2100.euphobos.ru/maps/

**Comment by Zispah** [comment]
> There is unofficial map portal at https://wz2100.euphobos.ru/maps/

What about mods? It is impossible to browse them if they are separate repositories on GitHub.

**Comment by past-due** [comment]
This link has now been added to the new Maps Database: https://maps.wz2100.net
